// <auto-generated />
using System;
using BlueArchiveWebScrapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueArchiveWebScrapper.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BlueArchiveWebScrapper.Student", b =>
                {
                    b.Property<string>("charaName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("audioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("combatClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("designer")
                        .HasColumnType("TEXT");

                    b.Property<bool>("files")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hobbies")
                        .HasColumnType("TEXT");

                    b.Property<string>("illustrator")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pageImageFullUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pageImageProfileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("school")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("skinSet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("voice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weaponType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("charaName");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
