// <auto-generated />
using System;
using Main.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Scanner.Model.Student", b =>
                {
                    b.Property<string>("CharaName")
                        .HasColumnType("TEXT")
                        .HasColumnName("charaName");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("audioUrl");

                    b.Property<string>("Birthday")
                        .HasColumnType("TEXT")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Designer")
                        .HasColumnType("TEXT")
                        .HasColumnName("designer");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Hobbies")
                        .HasColumnType("TEXT")
                        .HasColumnName("hobbies");

                    b.Property<string>("Illustrator")
                        .HasColumnType("TEXT")
                        .HasColumnName("illustrator");

                    b.Property<string>("ImageFullUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("imageFullUrl");

                    b.Property<string>("ImageProfileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("imageProfileUrl");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lastName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pageUrl");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("releaseDate");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("school");

                    b.Property<string>("SkinSet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("skinSet");

                    b.Property<string>("SmallImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("smallImageUrl");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voice");

                    b.HasKey("CharaName");

                    b.HasIndex("CharaName");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
